dependencies:
  - smartcontractkit/chainlink@1.2.1
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink@1.2.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
dotenv: .env
networks:
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: Ture
  development:
    verify: False
  win-gui:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
